export const ISSUE_SHEETS = ["2014", "2015", "2016", "2017", "2018", "2019"];
export const USER_TABLE = {
    "1098562": "JamieJohnson@iheartmedia.com",
    "1104436": "EliseMasanga@iheartmedia.com",
    "1104800": "LeeIsles@iheartmedia.com",
    "1109123": "ChristopherMessina@iheartmedia.com",
    "1109319": "JoshStigall@iheartmedia.com",
    "1109610": "GlendaBautista@iheartmedia.com",
    "1109751": "TrinaKing@iheartmedia.com",
    "1109761": "DanielleKwong@iHeartmedia.com",
    "1110037": "MartaRuiz@iHeartMedia.com",
    "1110087": "LauraGalbraith@iheartmedia.com",
    "1110184": "BrendonRowe@iheartmedia.com",
    "1110204": "MattPena@iheartmedia.com",
    "1110604": "KailuoWang@iheartmedia.com",
    "1110663": "ChitraSelvaraj@iheartmedia.com",
    "1110924": "AlannaKitaeff@iheartmedia.com",
    "1111096": "JamesonStone@iheartmedia.com",
    "1111362": "KaviHalemane@iheartmedia.com",
    "1111408": "DavidSerra@iheartmedia.com",
    "1111723": "BenAllison@iheartmedia.com",
    "1112033": "HeidyGarcia@iheartmedia.com",
    "1112034": "SeanFarrell@iheartmedia.com",
    "1112062": "AshlinOcampo@iheartmedia.com",
    "1112116": "CourtneyReges@iheartmedia.com",
    "1112284": "LillianSu@iheartmedia.com",
    "1112324": "ChaoLin@iheartmedia.com",
    "1112325": "MattEnglish@iheartmedia.com",
    "1112348": "VictoriaVanArsdale@iheartmedia.com",
    "1112373": "MorganReed@iheartmedia.com",
    "1112946": "AlexCompanioni@iheartmedia.com",
    "1113187": "JosephPrice@iheartmedia.com",
    "1113205": "NghiHuynh@iheartmedia.com",
    "1113313": "YehudaRosen@iheartmedia.com",
    "1113379": "DavidNaeder@iheartmedia.com",
    "1113864": "NajahMustafa@iheartmedia.com",
    "1114537": "ZackStayman@iheartmedia.com",
    "1114558": "AndrewVickory@iheartmedia.com",
    "1114886": "RashadArafeh@iheartmedia.com",
    "1115091": "BriannaPhillips@iheartmedia.com",
    "1115445": "JoshuaZizmor@iheartmedia.com",
    "1115488": "RachelLongley@iheartmedia.com",
    "1115730": "VictorChan@iheartmedia.com",
    "1115797": "DmitrySaprykin@iheartmedia.com",
    "1116329": "SamuelWatkinson@iheartmedia.com",
    "1116506": "RalphGrajo@iheartmedia.com",
    "1116624": "DavidBarratt@iheartmedia.com",
    "1117167": "MatthewHardardt@iheartmedia.com",
    "1117299": "BrettVintch@iheartmedia.com",
    "1117510": "WayneSeymour@iheartmedia.com",
    "1118371": "eamonbd@iheartmedia.com",
    "1118481": "SamOrpol@iheartmedia.com",
    "1118626": "ChristopherLavinio@iheartmedia.com",
    "1118996": "LinaNguyen@iheartmedia.com",
    "1119007": "GregCerchione@iheartmedia.com",
    "1119594": "duncan@prometheussoftware.ca",
    "1119767": "MarkCahill@iheartmedia.com",
    "1120072": "SavannaRovira@iheartmedia.com",
    "1120268": "UtaKnablein@iheartmedia.com",
    "1120341": "KrishnaGlick@iheartmedia.com",
    "1120884": "AlexBeach@iheartmedia.com",
    "1121542": "ShilpaBhagat@iheartmedia.com",
    "1121617": "JavierPonce@iheartmedia.com",
    "1123129": "IdanWaisman@iheartmedia.com",
    "1123334": "BernadettKristof@iheartmedia.com",
    "1123470": "CindyLo@iheartmedia.com",
    "1123549": "MaximilianoAyala@iheartmedia.com",
    "1123982": "ppatel@prometheussoftware.ca",
    "1124769": "JoshuaHarris@iheartmedia.com",
    amamut: "AlexMamut@iheartmedia.com",
    fozduran: "FerhatOzduran@iheartmedia.com",
    kchoe: "KerryChoe@iheartmedia.com",
    khayden: "KeithHayden@iheartmedia.com",
    mbrown: "MattBrown@iheartmedia.com",
    tmatsumoto: "TaichiMatsumoto@iheartmedia.com",
    aclements: "AaronClements@iheartmedia.com",
    aroberts: "AdamRoberts@iheartmedia.com",
    bbennett: "BrianBennett@iheartmedia.com",
    cccnyc1ars: "AlanSum@iheartmedia.com",
    cccnyc1avp: "AmitPatel@iheartmedia.com",
    cccnyc1cab: "CarolynBraza@iheartmedia.com",
    cccnyc1cma: "coreykahn@iheartmedia.com",
    cccnyc1dbl: "DavidLevine@iheartmedia.com",
    cccnyc1gip: "GracePaet@iheartmedia.com",
    cccnyc1ixk: "IrinaKaprizkina@iheartmedia.com",
    cccnyc1jxc: "JosephChisari@iheartmedia.com",
    cccnyc1khp: "Kristen@iheartmedia.com",
    cccnyc1kmz: "KarolZapolski@iheartmedia.com",
    cccnyc1njt: "NateTobin2@iheartmedia.com",
    cccnyc1rcd: "RyanDavis@iheartmedia.com",
    cccnyc1sxs: "SusanaSoares@iheartmedia.com",
    cccnyc1tmj: "TheresaJontz@iheartmedia.com",
    cccpeo1ajz: "AnthonyZic@iheartmedia.com",
    ccrbdl1mje: "MarkEscott@iheartmedia.com",
    ccrlax1dat: "DanThom@iheartmedia.com",
    ccrlax1nbc: "NoahCaldwell@iheartmedia.com",
    ccrlax1pit: "PeterTeitelbaum@iheartmedia.com",
    ccrnyc1jxe: "JaimeEndemano@iheartmedia.com",
    ccrnyc1krs: "KeenonSnell@iheartmedia.com",
    ccrnyc1mcr: "MichaelReichard@iheartmedia.com",
    ccrnyc1rar: "RobRowe@iheartmedia.com",
    ccrnyc1rrs: "RyanSult@iheartmedia.com",
    ccrnyc1rxt: "RenatoTiczon@iheartmedia.com",
    ccrnyc2ajm: "AnthonyMolaee@iheartmedia.com",
    ccrnyc2msw: "MikeWoodruff@iheartmedia.com",
    ccrnyc2rag: "RyanGoff@iheartmedia.com",
    ccrsea1scg: "ShawnGarrett@iheartmedia.com",
    ccrsea1smt: "SethThompson@iheartmedia.com",
    ccrwas1elc: "EricCogan@iheartmedia.com",
    cli: "ChunanLi@iheartmedia.com",
    "con-ccrnyc1dot": "DowneyTung@iHeartMedia.com",
    "con-nyc1pp": "ppatel@prometheussoftware.ca",
    "con-nyc2lhill": "lance@prometheussoftware.ca",
    "con-nyc2sxw": "ScottWilkin@clearchannel.com",
    cwilliams: "ChrisWilliams@iheartmedia.com",
    gmiller: "GabeMiller@iheartmedia.com",
    gvilches: "GeorgeVilches@iHeartMedia.com",
    howella: "AdamHowell@iheartmedia.com",
    jpatterson: "JasonPatterson@iheartmedia.com",
    kshaik: "KristinaShaik@iheartmedia.com",
    lbedner: "LeonardBedner@iheartmedia.com",
    lhamre: "LasseHamre@iheartmedia.com",
    lvauthrin: "LaurentVauthrin@iheartmedia.com",
    mberger: "MattBerger@iheartmedia.com",
    mbiondo: "MichaelBiondo@iheartmedia.com",
    mfielder: "MatthewFielder@iheartmedia.com",
    mfitzpatric: "mhibbard@iheartmedia.com",
    msawyer: "MarkSawyer@iheartmedia.com",
    pkankipati: "PadmajaKankipati@iheartmedia.com",
    prebur1hpp: "HPatel@premierenetworks.com",
    rbhatia: "RaviBhatia@iheartmedia.com",
    skutty: "SreekalaKutty@iheartmedia.com",
    somorris: "SpencerMorris@iheartmedia.com",
    sradley: "StevenRadley@iheartmedia.com",
    stropeano: "StevenTropeano@iheartmedia.com",
    tdrapeau: "ThomasDrapeau@iheartmedia.com",
    tgoldberg: "ToddGoldberg@iheartmedia.com",
    tlong: "TreyLong@iheartmedia.com",
    tterry: "TravisTerry@iheartmedia.com",
    uanjum: "UzminaAnjum@iheartmedia.com",
};
export const USER_COLS = ["Assignee", "Reporter", "Creator", "Watchers"];
export const DATE_COLS = ["Created", "Updated", "Resolved"];
export const PROJ_OLD_KEY = "AR";
export const PROJ_NEW_KEY = "IHRAR";
export const WANTED_COLS = [
    "Summary",
    "Issue key",
    "Issue id",
    "Parent id",
    "Issue Type",
    "Status",
    "Project key",
    "Resolution",
    "Assignee",
    "Reporter",
    "Creator",
    "Created",
    "Updated",
    "Resolved",
    "Fix Version/s",
    "Labels",
    "Description",
    "Custom field (Acceptance Criteria)",
    "Custom field (Capitalizable)",
    "Custom field (Epic Colour)",
    "Custom field (Epic Link)",
    "Custom field (Epic Name)",
    "Custom field (Epic Status)",
    "Custom field (Steps to Reproduce)",
    "Custom field (Story Points)",
    "Custom field (TestEng Required)",
    "Custom field (Testing Notes)",
    // MULTI
    "Component/s",
    "Watchers",
    "Outward issue link (Blocks)",
    "Outward issue link (Bug of)",
    "Outward issue link (Cloners)",
    "Outward issue link (Dependency)",
    "Outward issue link (Duplicate)",
    "Outward issue link (Mention)",
    "Outward issue link (Parent-Child)",
    "Outward issue link (Relates)",
    "Outward issue link (Resolved Bugs/Defect)",
    "Outward issue link (Workaround)",
    "Attachment",
    "Sprint",
    "Comment",
];
